// src/sections/Products/useProducts.js
import { useMemo } from 'react';
import msiProductImage from '../../assets/0db52e21-46c0-4fbd-a3d5-487dcb7be6b0.png';
import msiPro from '../../assets/ac9da762-3a89-4944-a88a-624d07d57622.png';
import msiPro1 from '../../assets/81e34b10-3129-4520-ab02-ad75d0d297b1.png';
import msiPro2 from '../../assets/beda4027-6c88-47da-9e63-0bb3cf22a8f9.png';
import msip from "../../assets/image 29.svg";

export const useProducts = () => {
  const products = useMemo(() => [
    // LAPTOPS
    {
      id: 1,
      status: "in stock",
      image: msiPro,
      rating: 5,
      reviews: 24,
      name: "MSI GF63 Thin 11UC Gaming Laptop - Intel i5-11400H, RTX 3050, 15.6\" FHD",
      oldPrice: 1299.00,
      price: 1099.00,
      category: "Laptops",
      brand: "MSI",
      priceRange: "$1,000.00 - $2,000.00",
      color: "black"
    },
    {
      id: 2,
      status: "in stock",
      image: msiProductImage,
      rating: 4,
      reviews: 18,
      name: "ASUS ROG Strix G15 Gaming Laptop - AMD Ryzen 7, RTX 4060, 15.6\" 144Hz",
      oldPrice: 1799.00,
      price: 1599.00,
      category: "Laptops",
      brand: "ASUS",
      priceRange: "$1,000.00 - $2,000.00",
      color: "black"
    },
    {
      id: 3,
      status: "in stock",
      image: msiPro1,
      rating: 5,
      reviews: 32,
      name: "HP Pavilion 15 Business Laptop - Intel i7-12700H, 16GB RAM, 512GB SSD",
      oldPrice: 999.00,
      price: 849.00,
      category: "Laptops",
      brand: "HP",
      priceRange: "$0.00 - $1,000.00",
      color: "silver"
    },
    {
      id: 4,
      status: "check availability",
      image: msiPro2,
      rating: 4,
      reviews: 15,
      name: "Dell XPS 13 Ultrabook - Intel i7-13700H, 32GB RAM, 1TB SSD, 13.4\" 4K",
      oldPrice: 2499.00,
      price: 2199.00,
      category: "Laptops",
      brand: "Dell",
      priceRange: "$2,000.00 - $3,000.00",
      color: "silver"
    },
    {
      id: 5,
      status: "in stock",
      image: msip,
      rating: 5,
      reviews: 28,
      name: "Lenovo ThinkPad E15 Business Laptop - Intel i5-12500H, 16GB, 512GB",
      oldPrice: 1199.00,
      price: 999.00,
      category: "Laptops",
      brand: "Lenovo",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },
    {
      id: 6,
      status: "in stock",
      image: msiPro,
      rating: 4,
      reviews: 21,
      name: "Acer Nitro 5 Gaming Laptop - AMD Ryzen 5, GTX 1650, 15.6\" FHD 120Hz",
      oldPrice: 899.00,
      price: 749.00,
      category: "Laptops",
      brand: "Acer",
      priceRange: "$0.00 - $1,000.00",
      color: "red"
    },

    // DESKTOP PCs
    {
      id: 7,
      status: "in stock",
      image: msiProductImage,
      rating: 5,
      reviews: 19,
      name: "MSI Aegis RS 13 Gaming Desktop - Intel i7-13700F, RTX 4070, 32GB RAM",
      oldPrice: 2799.00,
      price: 2499.00,
      category: "Desktop PCs",
      brand: "MSI",
      priceRange: "$2,000.00 - $3,000.00",
      color: "black"
    },
    {
      id: 8,
      status: "in stock",
      image: msiPro1,
      rating: 4,
      reviews: 16,
      name: "HP Pavilion Desktop - AMD Ryzen 5, 16GB RAM, 1TB HDD + 256GB SSD",
      oldPrice: 899.00,
      price: 749.00,
      category: "Desktop PCs",
      brand: "HP",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },
    {
      id: 9,
      status: "in stock",
      image: msiPro2,
      rating: 5,
      reviews: 23,
      name: "Dell OptiPlex 7000 Business Desktop - Intel i5-12500, 16GB, 512GB SSD",
      oldPrice: 1299.00,
      price: 1099.00,
      category: "Desktop PCs",
      brand: "Dell",
      priceRange: "$1,000.00 - $2,000.00",
      color: "black"
    },
    {
      id: 10,
      status: "check availability",
      image: msip,
      rating: 4,
      reviews: 12,
      name: "ASUS ROG Strix GT35 Gaming Desktop - Intel i9-12900F, RTX 4080, 32GB",
      oldPrice: 3499.00,
      price: 3199.00,
      category: "Desktop PCs",
      brand: "ASUS",
      priceRange: "$3,000.00 - $4,000.00",
      color: "black"
    },

    // NETWORKING DEVICES
    {
      id: 11,
      status: "in stock",
      image: msiPro,
      rating: 4,
      reviews: 45,
      name: "ASUS AX6000 WiFi 6 Router - Dual Band Gigabit Wireless Router",
      oldPrice: 399.00,
      price: 329.00,
      category: "Networking Devices",
      brand: "ASUS",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },
    {
      id: 12,
      status: "in stock",
      image: msiProductImage,
      rating: 5,
      reviews: 38,
      name: "Netgear Nighthawk AX12 WiFi 6 Router - 12-Stream Dual Band",
      oldPrice: 499.00,
      price: 429.00,
      category: "Networking Devices",
      brand: "Netgear",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },
    {
      id: 13,
      status: "in stock",
      image: msiPro1,
      rating: 4,
      reviews: 29,
      name: "TP-Link Archer AX73 WiFi 6 Router - Dual Band Gigabit",
      oldPrice: 199.00,
      price: 159.00,
      category: "Networking Devices",
      brand: "TP-Link",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },
    {
      id: 14,
      status: "in stock",
      image: msiPro2,
      rating: 5,
      reviews: 52,
      name: "Ubiquiti UniFi Dream Machine - All-in-One Security Gateway",
      oldPrice: 699.00,
      price: 629.00,
      category: "Networking Devices",
      brand: "Ubiquiti",
      priceRange: "$0.00 - $1,000.00",
      color: "white"
    },

    // PRINTERS & SCANNERS
    {
      id: 15,
      status: "in stock",
      image: msip,
      rating: 4,
      reviews: 67,
      name: "HP LaserJet Pro M404n Monochrome Laser Printer",
      oldPrice: 299.00,
      price: 249.00,
      category: "Printers & Scanners",
      brand: "HP",
      priceRange: "$0.00 - $1,000.00",
      color: "white"
    },
    {
      id: 16,
      status: "in stock",
      image: msiPro,
      rating: 5,
      reviews: 43,
      name: "Canon PIXMA TR8620 All-in-One Wireless Inkjet Printer",
      oldPrice: 199.00,
      price: 159.00,
      category: "Printers & Scanners",
      brand: "Canon",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },
    {
      id: 17,
      status: "check availability",
      image: msiProductImage,
      rating: 4,
      reviews: 31,
      name: "Epson EcoTank ET-4760 All-in-One Supertank Printer",
      oldPrice: 449.00,
      price: 399.00,
      category: "Printers & Scanners",
      brand: "Epson",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },
    {
      id: 18,
      status: "in stock",
      image: msiPro1,
      rating: 5,
      reviews: 28,
      name: "Brother MFC-L3770CDW Color All-in-One Laser Printer",
      oldPrice: 599.00,
      price: 529.00,
      category: "Printers & Scanners",
      brand: "Brother",
      priceRange: "$0.00 - $1,000.00",
      color: "white"
    },

    // PC PARTS
    {
      id: 19,
      status: "in stock",
      image: msiPro2,
      rating: 5,
      reviews: 89,
      name: "MSI GeForce RTX 4070 Gaming X Trio 12GB GDDR6X Graphics Card",
      oldPrice: 1299.00,
      price: 1199.00,
      category: "PC Parts",
      brand: "MSI",
      priceRange: "$1,000.00 - $2,000.00",
      color: "black"
    },
    {
      id: 20,
      status: "in stock",
      image: msip,
      rating: 4,
      reviews: 76,
      name: "AMD Ryzen 7 7700X 8-Core Desktop Processor",
      oldPrice: 449.00,
      price: 399.00,
      category: "PC Parts",
      brand: "AMD",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },
    {
      id: 21,
      status: "in stock",
      image: msiPro,
      rating: 5,
      reviews: 54,
      name: "ASUS ROG Strix B650E-E Gaming WiFi Motherboard",
      oldPrice: 399.00,
      price: 349.00,
      category: "PC Parts",
      brand: "ASUS",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },
    {
      id: 22,
      status: "in stock",
      image: msiProductImage,
      rating: 4,
      reviews: 92,
      name: "Corsair Vengeance LPX 32GB (2x16GB) DDR4 3200MHz RAM",
      oldPrice: 199.00,
      price: 169.00,
      category: "PC Parts",
      brand: "Corsair",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },
    {
      id: 23,
      status: "out of stock",
      image: msiPro1,
      rating: 5,
      reviews: 67,
      name: "Samsung 980 PRO 2TB NVMe M.2 Internal SSD",
      oldPrice: 299.00,
      price: 249.00,
      category: "PC Parts",
      brand: "Samsung",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },

    // ALL OTHER PRODUCTS (Monitors, Accessories, etc.)
    {
      id: 24,
      status: "in stock",
      image: msiPro2,
      rating: 5,
      reviews: 156,
      name: "MSI Optix MAG274QRF-QD 27\" 165Hz QHD Gaming Monitor",
      oldPrice: 699.00,
      price: 599.00,
      category: "All Other Products",
      brand: "MSI",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },
    {
      id: 25,
      status: "in stock",
      image: msip,
      rating: 4,
      reviews: 89,
      name: "ASUS TUF Gaming VG27AQ 27\" 165Hz IPS Gaming Monitor",
      oldPrice: 449.00,
      price: 379.00,
      category: "All Other Products",
      brand: "ASUS",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },
    {
      id: 26,
      status: "in stock",
      image: msiPro,
      rating: 5,
      reviews: 234,
      name: "Logitech MX Master 3S Wireless Mouse - Graphite",
      oldPrice: 129.00,
      price: 99.00,
      category: "All Other Products",
      brand: "Logitech",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },
    {
      id: 27,
      status: "in stock",
      image: msiProductImage,
      rating: 4,
      reviews: 178,
      name: "Corsair K95 RGB Platinum XT Mechanical Gaming Keyboard",
      oldPrice: 249.00,
      price: 199.00,
      category: "All Other Products",
      brand: "Corsair",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },
    {
      id: 28,
      status: "check availability",
      image: msiPro1,
      rating: 5,
      reviews: 145,
      name: "SteelSeries Arctis 7P Wireless Gaming Headset",
      oldPrice: 199.00,
      price: 159.00,
      category: "All Other Products",
      brand: "SteelSeries",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },

    // MORE LAPTOPS (29-50)
    {
      id: 29,
      status: "in stock",
      image: msiPro2,
      rating: 4,
      reviews: 67,
      name: "MacBook Air M2 13-inch - 8GB RAM, 256GB SSD, Space Gray",
      oldPrice: 1299.00,
      price: 1199.00,
      category: "Laptops",
      brand: "Apple",
      priceRange: "$1,000.00 - $2,000.00",
      color: "gray"
    },
    {
      id: 30,
      status: "in stock",
      image: msip,
      rating: 5,
      reviews: 89,
      name: "Surface Laptop 5 - Intel i7, 16GB RAM, 512GB SSD, Platinum",
      oldPrice: 1899.00,
      price: 1699.00,
      category: "Laptops",
      brand: "Microsoft",
      priceRange: "$1,000.00 - $2,000.00",
      color: "silver"
    },
    {
      id: 31,
      status: "check availability",
      image: msiPro,
      rating: 4,
      reviews: 45,
      name: "Razer Blade 15 Gaming Laptop - RTX 4070, Intel i7, 32GB RAM",
      oldPrice: 2799.00,
      price: 2499.00,
      category: "Laptops",
      brand: "Razer",
      priceRange: "$2,000.00 - $3,000.00",
      color: "black"
    },
    {
      id: 32,
      status: "in stock",
      image: msiProductImage,
      rating: 4,
      reviews: 34,
      name: "Alienware m15 R7 Gaming Laptop - RTX 3080, AMD Ryzen 9",
      oldPrice: 2999.00,
      price: 2699.00,
      category: "Laptops",
      brand: "Dell",
      priceRange: "$2,000.00 - $3,000.00",
      color: "black"
    },
    {
      id: 33,
      status: "in stock",
      image: msiPro1,
      rating: 5,
      reviews: 78,
      name: "ThinkPad X1 Carbon Gen 10 - Intel i7, 16GB RAM, 1TB SSD",
      oldPrice: 2199.00,
      price: 1899.00,
      category: "Laptops",
      brand: "Lenovo",
      priceRange: "$1,000.00 - $2,000.00",
      color: "black"
    },
    {
      id: 34,
      status: "in stock",
      image: msiPro2,
      rating: 4,
      reviews: 56,
      name: "Predator Helios 300 Gaming Laptop - RTX 4060, Intel i5",
      oldPrice: 1599.00,
      price: 1399.00,
      category: "Laptops",
      brand: "Acer",
      priceRange: "$1,000.00 - $2,000.00",
      color: "black"
    },
    {
      id: 35,
      status: "out of stock",
      image: msip,
      rating: 5,
      reviews: 123,
      name: "MacBook Pro 14-inch M2 Pro - 16GB RAM, 512GB SSD",
      oldPrice: 2499.00,
      price: 2299.00,
      category: "Laptops",
      brand: "Apple",
      priceRange: "$2,000.00 - $3,000.00",
      color: "silver"
    },
    {
      id: 36,
      status: "in stock",
      image: msiPro,
      rating: 4,
      reviews: 67,
      name: "ZenBook Pro 15 OLED - Intel i9, RTX 3050 Ti, 32GB RAM",
      oldPrice: 2299.00,
      price: 1999.00,
      category: "Laptops",
      brand: "ASUS",
      priceRange: "$1,000.00 - $2,000.00",
      color: "blue"
    },
    {
      id: 37,
      status: "in stock",
      image: msiProductImage,
      rating: 4,
      reviews: 89,
      name: "Spectre x360 14 Convertible - Intel i7, 16GB RAM, 1TB SSD",
      oldPrice: 1799.00,
      price: 1599.00,
      category: "Laptops",
      brand: "HP",
      priceRange: "$1,000.00 - $2,000.00",
      color: "gold"
    },
    {
      id: 38,
      status: "check availability",
      image: msiPro1,
      rating: 5,
      reviews: 45,
      name: "Legion 5 Pro Gaming Laptop - RTX 4070, AMD Ryzen 7",
      oldPrice: 1899.00,
      price: 1699.00,
      category: "Laptops",
      brand: "Lenovo",
      priceRange: "$1,000.00 - $2,000.00",
      color: "black"
    },

    // MORE DESKTOP PCs (39-50)
    {
      id: 39,
      status: "in stock",
      image: msiPro2,
      rating: 5,
      reviews: 78,
      name: "iMac 24-inch M2 - 8GB RAM, 256GB SSD, Blue",
      oldPrice: 1499.00,
      price: 1299.00,
      category: "Desktop PCs",
      brand: "Apple",
      priceRange: "$1,000.00 - $2,000.00",
      color: "blue"
    },
    {
      id: 40,
      status: "in stock",
      image: msip,
      rating: 4,
      reviews: 56,
      name: "Alienware Aurora R13 Gaming Desktop - RTX 4080, Intel i9",
      oldPrice: 3499.00,
      price: 3199.00,
      category: "Desktop PCs",
      brand: "Dell",
      priceRange: "$3,000.00 - $4,000.00",
      color: "black"
    },
    {
      id: 41,
      status: "in stock",
      image: msiPro,
      rating: 4,
      reviews: 67,
      name: "ThinkCentre M90q Tiny Desktop - Intel i5, 16GB RAM",
      oldPrice: 999.00,
      price: 849.00,
      category: "Desktop PCs",
      brand: "Lenovo",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },
    {
      id: 42,
      status: "check availability",
      image: msiProductImage,
      rating: 5,
      reviews: 89,
      name: "Predator Orion 7000 Gaming Desktop - RTX 4090, Intel i9",
      oldPrice: 4299.00,
      price: 3899.00,
      category: "Desktop PCs",
      brand: "Acer",
      priceRange: "$3,000.00 - $4,000.00",
      color: "black"
    },
    {
      id: 43,
      status: "in stock",
      image: msiPro1,
      rating: 4,
      reviews: 45,
      name: "Surface Studio 2+ All-in-One - Intel i7, 32GB RAM",
      oldPrice: 4499.00,
      price: 4199.00,
      category: "Desktop PCs",
      brand: "Microsoft",
      priceRange: "$4,000.00+",
      color: "silver"
    },
    {
      id: 44,
      status: "in stock",
      image: msiPro2,
      rating: 5,
      reviews: 123,
      name: "ROG Strix GT15 Gaming Desktop - RTX 4070, AMD Ryzen 7",
      oldPrice: 2299.00,
      price: 1999.00,
      category: "Desktop PCs",
      brand: "ASUS",
      priceRange: "$1,000.00 - $2,000.00",
      color: "black"
    },

    // MORE NETWORKING DEVICES (45-60)
    {
      id: 45,
      status: "in stock",
      image: msip,
      rating: 4,
      reviews: 234,
      name: "Linksys Velop AX4200 Mesh WiFi 6 System (3-pack)",
      oldPrice: 399.00,
      price: 329.00,
      category: "Networking Devices",
      brand: "Linksys",
      priceRange: "$0.00 - $1,000.00",
      color: "white"
    },
    {
      id: 46,
      status: "in stock",
      image: msiPro,
      rating: 5,
      reviews: 156,
      name: "Eero Pro 6E Mesh WiFi System (3-pack)",
      oldPrice: 599.00,
      price: 499.00,
      category: "Networking Devices",
      brand: "Amazon",
      priceRange: "$0.00 - $1,000.00",
      color: "white"
    },
    {
      id: 47,
      status: "check availability",
      image: msiProductImage,
      rating: 4,
      reviews: 89,
      name: "D-Link DIR-X6060 AX6000 WiFi 6 Router",
      oldPrice: 349.00,
      price: 299.00,
      category: "Networking Devices",
      brand: "D-Link",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },
    {
      id: 48,
      status: "in stock",
      image: msiPro1,
      rating: 5,
      reviews: 67,
      name: "Cisco Meraki MX68 Security Appliance",
      oldPrice: 899.00,
      price: 799.00,
      category: "Networking Devices",
      brand: "Cisco",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },

    // MORE PRINTERS & SCANNERS (49-65)
    {
      id: 49,
      status: "in stock",
      image: msiPro2,
      rating: 4,
      reviews: 234,
      name: "Xerox VersaLink C405 Color Multifunction Printer",
      oldPrice: 899.00,
      price: 799.00,
      category: "Printers & Scanners",
      brand: "Xerox",
      priceRange: "$0.00 - $1,000.00",
      color: "white"
    },
    {
      id: 50,
      status: "check availability",
      image: msip,
      rating: 5,
      reviews: 156,
      name: "Ricoh SP 330DN Monochrome Laser Printer",
      oldPrice: 249.00,
      price: 199.00,
      category: "Printers & Scanners",
      brand: "Ricoh",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },
    {
      id: 51,
      status: "in stock",
      image: msiPro,
      rating: 4,
      reviews: 89,
      name: "Lexmark CX331adwe Color Multifunction Printer",
      oldPrice: 399.00,
      price: 349.00,
      category: "Printers & Scanners",
      brand: "Lexmark",
      priceRange: "$0.00 - $1,000.00",
      color: "white"
    },
    {
      id: 52,
      status: "in stock",
      image: msiProductImage,
      rating: 5,
      reviews: 67,
      name: "Fujitsu ScanSnap iX1600 Document Scanner",
      oldPrice: 499.00,
      price: 449.00,
      category: "Printers & Scanners",
      brand: "Fujitsu",
      priceRange: "$0.00 - $1,000.00",
      color: "white"
    },

    // MORE PC PARTS (53-120)
    {
      id: 53,
      status: "in stock",
      image: msiPro1,
      rating: 5,
      reviews: 345,
      name: "NVIDIA GeForce RTX 4090 Founders Edition 24GB",
      oldPrice: 1799.00,
      price: 1599.00,
      category: "PC Parts",
      brand: "NVIDIA",
      priceRange: "$1,000.00 - $2,000.00",
      color: "black"
    },
    {
      id: 54,
      status: "in stock",
      image: msiPro2,
      rating: 4,
      reviews: 234,
      name: "Intel Core i9-13900K Desktop Processor",
      oldPrice: 649.00,
      price: 589.00,
      category: "PC Parts",
      brand: "Intel",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },
    {
      id: 55,
      status: "check availability",
      image: msip,
      rating: 5,
      reviews: 156,
      name: "G.Skill Trident Z5 RGB 32GB DDR5-6000 RAM Kit",
      oldPrice: 399.00,
      price: 349.00,
      category: "PC Parts",
      brand: "G.Skill",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },
    {
      id: 56,
      status: "in stock",
      image: msiPro,
      rating: 4,
      reviews: 289,
      name: "Western Digital Black SN850X 2TB NVMe SSD",
      oldPrice: 349.00,
      price: 299.00,
      category: "PC Parts",
      brand: "Western Digital",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },
    {
      id: 57,
      status: "in stock",
      image: msiProductImage,
      rating: 5,
      reviews: 123,
      name: "Corsair RM1000x 1000W 80+ Gold Modular PSU",
      oldPrice: 199.00,
      price: 179.00,
      category: "PC Parts",
      brand: "Corsair",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },
    {
      id: 58,
      status: "out of stock",
      image: msiPro1,
      rating: 4,
      reviews: 67,
      name: "NZXT Kraken X73 360mm AIO Liquid Cooler",
      oldPrice: 199.00,
      price: 169.00,
      category: "PC Parts",
      brand: "NZXT",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },
    {
      id: 59,
      status: "in stock",
      image: msiPro2,
      rating: 5,
      reviews: 178,
      name: "Fractal Design Define 7 Mid Tower Case",
      oldPrice: 179.00,
      price: 149.00,
      category: "PC Parts",
      brand: "Fractal Design",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },
    {
      id: 60,
      status: "in stock",
      image: msip,
      rating: 4,
      reviews: 234,
      name: "Gigabyte Z790 AORUS Elite AX DDR5 Motherboard",
      oldPrice: 299.00,
      price: 269.00,
      category: "PC Parts",
      brand: "Gigabyte",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },

    // MORE ALL OTHER PRODUCTS (61-178)
    {
      id: 61,
      status: "in stock",
      image: msiPro,
      rating: 5,
      reviews: 456,
      name: "LG 27GP950-B 27\" 4K 144Hz Gaming Monitor",
      oldPrice: 899.00,
      price: 799.00,
      category: "All Other Products",
      brand: "LG",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },
    {
      id: 62,
      status: "in stock",
      image: msiProductImage,
      rating: 4,
      reviews: 234,
      name: "Samsung Odyssey G7 32\" Curved Gaming Monitor",
      oldPrice: 699.00,
      price: 599.00,
      category: "All Other Products",
      brand: "Samsung",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },
    {
      id: 63,
      status: "check availability",
      image: msiPro1,
      rating: 5,
      reviews: 178,
      name: "Razer DeathAdder V3 Pro Wireless Gaming Mouse",
      oldPrice: 149.00,
      price: 129.00,
      category: "All Other Products",
      brand: "Razer",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },
    {
      id: 64,
      status: "in stock",
      image: msiPro2,
      rating: 4,
      reviews: 345,
      name: "HyperX Alloy Elite RGB Mechanical Keyboard",
      oldPrice: 129.00,
      price: 99.00,
      category: "All Other Products",
      brand: "HyperX",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },
    {
      id: 65,
      status: "in stock",
      image: msip,
      rating: 5,
      reviews: 267,
      name: "Audio-Technica ATH-M50xBT2 Wireless Headphones",
      oldPrice: 199.00,
      price: 169.00,
      category: "All Other Products",
      brand: "Audio-Technica",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },
    {
      id: 66,
      status: "out of stock",
      image: msiPro,
      rating: 4,
      reviews: 123,
      name: "Elgato Stream Deck MK.2 Content Creation Controller",
      oldPrice: 149.00,
      price: 129.00,
      category: "All Other Products",
      brand: "Elgato",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },
    {
      id: 67,
      status: "in stock",
      image: msiProductImage,
      rating: 5,
      reviews: 189,
      name: "Blue Yeti USB Microphone - Blackout",
      oldPrice: 129.00,
      price: 99.00,
      category: "All Other Products",
      brand: "Blue",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },
    {
      id: 68,
      status: "in stock",
      image: msiPro1,
      rating: 4,
      reviews: 234,
      name: "Logitech C920s HD Pro Webcam",
      oldPrice: 99.00,
      price: 79.00,
      category: "All Other Products",
      brand: "Logitech",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },
    {
      id: 69,
      status: "check availability",
      image: msiPro2,
      rating: 5,
      reviews: 156,
      name: "Rode PodMic USB Dynamic Microphone",
      oldPrice: 199.00,
      price: 179.00,
      category: "All Other Products",
      brand: "Rode",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    },
    {
      id: 70,
      status: "in stock",
      image: msip,
      rating: 4,
      reviews: 89,
      name: "Anker PowerCore 26800 Portable Charger",
      oldPrice: 79.00,
      price: 59.00,
      category: "All Other Products",
      brand: "Anker",
      priceRange: "$0.00 - $1,000.00",
      color: "black"
    }
  ], []);

  // Category mapping for navigation
  const categories = {
    "Laptops": "Laptops",
    "Desktop PCs": "Desktop PCs",
    "Networking Devices": "Networking Devices",
    "Printers & Scanners": "Printers & Scanners",
    "PC Parts": "PC Parts",
    "All Other Products": "All Other Products",
    "Repairs": "Repairs"
  };

  // Get products by category
  const getProductsByCategory = (category) => {
    if (!category || category === 'all') return products;
    return products.filter(product => 
      product.category.toLowerCase() === category.toLowerCase()
    );
  };

  // Get products by brand within a category
  const getProductsByBrand = (category, brand) => {
    let filteredProducts = getProductsByCategory(category);
    if (brand && brand !== 'all') {
      filteredProducts = filteredProducts.filter(product => 
        product.brand?.toLowerCase() === brand.toLowerCase()
      );
    }
    return filteredProducts;
  };

  // Get unique brands for a category
  const getBrandsByCategory = (category) => {
    const categoryProducts = getProductsByCategory(category);
    const brands = [...new Set(categoryProducts.map(product => product.brand).filter(Boolean))];
    return brands.sort();
  };

  return { 
    products, 
    categories, 
    getProductsByCategory, 
    getProductsByBrand, 
    getBrandsByCategory 
  };
};